<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="33287" started-at="2023-03-16T16:11:46Z" finished-at="2023-03-16T16:12:20Z">
    <groups>
      <group name="sanity">
        <method signature="FaceebookClassTestNG.tc4()[pri:0, instance:org.testng.FaceebookClassTestNG@4b5a5ed1]" name="tc4" class="org.testng.FaceebookClassTestNG"/>
      </group> <!-- sanity -->
    </groups>
    <test name="Default test" duration-ms="33287" started-at="2023-03-16T16:11:46Z" finished-at="2023-03-16T16:12:20Z">
      <class name="org.testng.FaceebookClassTestNG">
        <test-method status="PASS" signature="tc1()[pri:0, instance:org.testng.FaceebookClassTestNG@4b5a5ed1]" name="tc1" is-config="true" duration-ms="2420" started-at="2023-03-16T16:11:46Z" finished-at="2023-03-16T16:11:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
        <test-method status="PASS" signature="tc4()[pri:0, instance:org.testng.FaceebookClassTestNG@4b5a5ed1]" name="tc4" duration-ms="22204" started-at="2023-03-16T16:11:49Z" finished-at="2023-03-16T16:12:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc4 -->
        <test-method status="PASS" signature="tc2()[pri:0, instance:org.testng.FaceebookClassTestNG@4b5a5ed1]" name="tc2" is-config="true" duration-ms="0" started-at="2023-03-16T16:11:49Z" finished-at="2023-03-16T16:11:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="PASS" signature="tc3()[pri:0, instance:org.testng.FaceebookClassTestNG@4b5a5ed1]" name="tc3" is-config="true" duration-ms="0" started-at="2023-03-16T16:12:11Z" finished-at="2023-03-16T16:12:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method status="SKIP" signature="tc5()[pri:0, instance:org.testng.FaceebookClassTestNG@4b5a5ed1]" name="tc5" duration-ms="3514" started-at="2023-03-16T16:12:11Z" finished-at="2023-03-16T16:12:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.testng.FaceebookClassTestNG.tc5(FaceebookClassTestNG.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc5 -->
        <test-method status="PASS" signature="tc2()[pri:0, instance:org.testng.FaceebookClassTestNG@4b5a5ed1]" name="tc2" is-config="true" duration-ms="0" started-at="2023-03-16T16:12:11Z" finished-at="2023-03-16T16:12:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="SKIP" signature="tc5()[pri:0, instance:org.testng.FaceebookClassTestNG@4b5a5ed1]" name="tc5" duration-ms="2566" started-at="2023-03-16T16:12:15Z" finished-at="2023-03-16T16:12:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.testng.FaceebookClassTestNG.tc5(FaceebookClassTestNG.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc5 -->
        <test-method status="PASS" signature="tc2()[pri:0, instance:org.testng.FaceebookClassTestNG@4b5a5ed1]" name="tc2" is-config="true" duration-ms="0" started-at="2023-03-16T16:12:15Z" finished-at="2023-03-16T16:12:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="PASS" signature="tc3()[pri:0, instance:org.testng.FaceebookClassTestNG@4b5a5ed1]" name="tc3" is-config="true" duration-ms="0" started-at="2023-03-16T16:12:15Z" finished-at="2023-03-16T16:12:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method status="PASS" signature="tc2()[pri:0, instance:org.testng.FaceebookClassTestNG@4b5a5ed1]" name="tc2" is-config="true" duration-ms="0" started-at="2023-03-16T16:12:17Z" finished-at="2023-03-16T16:12:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="FAIL" signature="tc5()[pri:0, instance:org.testng.FaceebookClassTestNG@4b5a5ed1]" name="tc5" duration-ms="2538" started-at="2023-03-16T16:12:17Z" finished-at="2023-03-16T16:12:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.testng.FaceebookClassTestNG.tc5(FaceebookClassTestNG.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc5 -->
        <test-method status="PASS" signature="tc3()[pri:0, instance:org.testng.FaceebookClassTestNG@4b5a5ed1]" name="tc3" is-config="true" duration-ms="0" started-at="2023-03-16T16:12:17Z" finished-at="2023-03-16T16:12:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method status="PASS" signature="tc3()[pri:0, instance:org.testng.FaceebookClassTestNG@4b5a5ed1]" name="tc3" is-config="true" duration-ms="0" started-at="2023-03-16T16:12:20Z" finished-at="2023-03-16T16:12:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
      </class> <!-- org.testng.FaceebookClassTestNG -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
